### ISSUE TITLE
Right Alignment

### ISSUE THREAD

**Issue by NickStees** [AdamPS/rrssb-plus#1]
How can I properly right align the buttons? When they go into two columns the javascript seems to only be compatible with left alignments since padding-left is always added to adjust the space.

**Comment by AdamPS** [comment]
Thanks for the feedback.  Interestingly I had the exact same idea myself, and I wrote the code for it at almost the exact time that you raised this issue!  I have just pushed my local changes and created a new release.

**Comment by NickStees** [comment]
Awesome! Can't wait to give it a shot, was trying all my CSS tricks with no
success!
