### ISSUE TITLE
Instructions for use outside Drupal

### ISSUE THREAD

**Issue by wnoble2005** [AdamPS/rrssb-plus#2]
I simply downloaded and used your files in place of the original code, but yours do not work.  Please advise.

http://q4q.com/rrssb_plus/

versus original

http://q4q.com/rrssb/

Apparently the documentation for using the library outside Drupal is not provided.

**Comment by AdamPS** [comment]
Apologies you are quite right.  Almost all users of RRSSB+ are using it within Drupal, and this documentation got left out.  I will write it up properly as soon as I get a chance.

Basically the answer is to copy the layout of the [demo page](https://www.albanyweb.co.uk/rrssb-plus) by examining it in your browser debugger/inspector or looking at the source.

Look out for the section starting like this
`<div class="rrssb"`
`  <div class="rrssb-prefix"\>Share this page</div>`
`  <ul class="rrssb-buttons"\>`
`    <li class="rrssb-googleplus"\>`

As you can see it's similar to the original RRSSB, but not identical.

**Comment by wnoble2005** [comment]
Worked.  Thanks!
http://q4q.com/rrssb_plus/index2.html

**Comment by AdamPS** [comment]
Finally done!
