### ISSUE TITLE
Icons overlapping

### ISSUE THREAD

**Issue by joewhitsitt** [AdamPS/rrssb-plus#3]
Using the demo page https://www.albanyweb.co.uk/rrssb-plus I altered the configuration to use values the script prefers (undocumented otherwise), and the icons are overlapping.

![screen shot 2017-11-28 at 11 58 00 am](https://user-images.githubusercontent.com/4663676/33335763-93eaff54-d433-11e7-8354-1931d3c2b1be.png)

![screen shot 2017-11-28 at 11 58 20 am](https://user-images.githubusercontent.com/4663676/33335767-96e3c86c-d433-11e7-9dfe-7d169dc18ec1.png)

![screen shot 2017-11-28 at 11 58 44 am](https://user-images.githubusercontent.com/4663676/33335773-9b5400f6-d433-11e7-8388-5ddf26cdfc00.png)

Thinking I did my "worst" as suggested, I just tried to hide the prefix (reserved width = 0, max width = 0.1) and I got this:
![screen shot 2017-11-28 at 12 01 27 pm](https://user-images.githubusercontent.com/4663676/33335890-ff0742a2-d433-11e7-8de9-491b372cebaf.png)

Any insight how how to get this to work would be much appreciated.

**Comment by AdamPS** [comment]
Thanks for the report.  I have fixed a bug on the demo system (i.e. not a problem in the actual library code).  Please can you try again - I think it is working better now.

I spotted a second bug in the demo system - the "right-align buttons" box will break the buttons so please don't use it on the demo.  The library JS doesn't have code to handle the alignment changing without a page refresh.  Again this is a demo-only problem - on a real site, the alignment won't change without a page refresh.

**Comment by joewhitsitt** [comment]
Fair enough. Using the same config as above, I got these results:

![screen shot 2017-11-28 at 1 43 18 pm](https://user-images.githubusercontent.com/4663676/33340611-307d5764-d442-11e7-8af2-3d2c55b86b12.png)

and hide the prefix only config (reserved width = 0, max width = 0.1):
![screen shot 2017-11-28 at 1 47 18 pm](https://user-images.githubusercontent.com/4663676/33340801-b9826680-d442-11e7-9d0a-96ad5b9d94de.png)

**Comment by AdamPS** [comment]
I have just fixed another bug that I spotted with those specific settings: #4

**Comment by AdamPS** [comment]
And the right-align is now working in the demo
