### ISSUE TITLE
Non Drupal Installation / Instructions

### ISSUE THREAD

**Issue by taskmann** [AdamPS/rrssb-plus#5]
What I like about the original RSSB is the easy installation instruction they provide at their Github page.

I like the improvements listed for the fork. However, I can't figure out how to implement a working copy.

Thanks still.

**Comment by AdamPS** [comment]
Yes sorry I haven't written those - I am mostly focusing on the Drupal case.  However there is already an issue #2  , and there are some guidelines there.
