### ISSUE TITLE
Too much padding on mobile displays

### ISSUE THREAD

**Issue by ptmkenny** [AdamPS/rrssb-plus#7]
I'm using the RRSSB module on Drupal 8.9.1.  I'm noticing that there is way too much right padding on the RRSSB links.

For example, this is what I see when setting Chrome Developer Tools to iPhone 6:

<img width="365" alt="bartik_iphone678_toomuchpadding" src="https://user-images.githubusercontent.com/1451472/86018177-7ef02100-ba14-11ea-944d-50bd6dac1360.PNG">

I switched my theme to Bartik (so that none of my custom theme's changes might interfere).

When I look at the JS, the right padding is set to 35.52%, which doesn't make sense to me because this is a single-column layout so the buttons should fill close to 100% of the screen width.

**Comment by AdamPS** [comment]
I don't really have enough information to help you.  The library has settings to control the appearance.  If you would like bigger buttons then you can set a larger size.  If you want a single column then set the minimum rows to 99.
