### ISSUE TITLE
Please update composer package to 0.5.3

### ISSUE THREAD

**Issue by parisek** [AdamPS/rrssb-plus#9]
Hello,

please update https://packagist.org/packages/rrssb/rrssb-plus for [0.5.3](https://github.com/AdamPS/rrssb-plus/releases/tag/0.5.3) version.

Thank you

**Comment by AdamPS** [comment]
Done. 0.5.3 was corrupt so made a new release 0.5.4.

**Comment by parisek** [comment]
Thank you
